"""empty message

Revision ID: 279eca00035c
Revises: cefea6f4d3a8
Create Date: 2023-10-26 17:19:26.563413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279eca00035c'
down_revision = 'cefea6f4d3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamerelations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('fk_games_challenged_id_games', type_='foreignkey')
        batch_op.drop_constraint('fk_games_challenger_id_games', type_='foreignkey')
        batch_op.drop_column('challenger_id')
        batch_op.drop_column('challenged_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenged_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('challenger_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_games_challenger_id_games', 'games', ['challenger_id'], ['id'])
        batch_op.create_foreign_key('fk_games_challenged_id_games', 'games', ['challenged_id'], ['id'])

    op.drop_table('gamerelations')
    # ### end Alembic commands ###
