"""empty message

Revision ID: 65e10cb07a46
Revises: 27fbd979d41c
Create Date: 2023-10-26 17:43:42.640906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e10cb07a46'
down_revision = '27fbd979d41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('victories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('victor', sa.Integer(), nullable=True),
    sa.Column('loser', sa.Integer(), nullable=True),
    sa.Column('rating_gain', sa.Integer(), nullable=True),
    sa.Column('rating_loss', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_victories_game_id_games')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('victories')
    # ### end Alembic commands ###
