"""empty message

Revision ID: 79023fed2d24
Revises: 22bdad77855b
Create Date: 2023-10-29 00:15:42.972358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79023fed2d24'
down_revision = '22bdad77855b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('settings',
               existing_type=sa.VARCHAR(),
               type_=sa.PickleType(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('settings',
               existing_type=sa.PickleType(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
