"""empty message

Revision ID: 8975a8a455b2
Revises: 89f73186f989
Create Date: 2023-10-26 16:30:32.861291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8975a8a455b2'
down_revision = '89f73186f989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('victor', sa.Integer(), nullable=True),
    sa.Column('challenger_id', sa.Integer(), nullable=True),
    sa.Column('challenged_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenged_id'], ['users.id'], name=op.f('fk_games_challenged_id_users')),
    sa.ForeignKeyConstraint(['challenger_id'], ['users.id'], name=op.f('fk_games_challenger_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
