"""empty message

Revision ID: cefea6f4d3a8
Revises: 8975a8a455b2
Create Date: 2023-10-26 16:48:07.842318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cefea6f4d3a8'
down_revision = '8975a8a455b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('fk_games_challenger_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_games_challenged_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_games_challenger_id_games'), 'games', ['challenger_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_games_challenged_id_games'), 'games', ['challenged_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_games_challenged_id_games'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_games_challenger_id_games'), type_='foreignkey')
        batch_op.create_foreign_key('fk_games_challenged_id_users', 'users', ['challenged_id'], ['id'])
        batch_op.create_foreign_key('fk_games_challenger_id_users', 'users', ['challenger_id'], ['id'])

    # ### end Alembic commands ###
